name = "winzi-status"
main = "src/worker.js"
compatibility_date = "2024-12-01"

[vars]
TWITCH_LOGIN = "winzilp"
KICK_SLUG = "winzi"
ALLOWED_ORIGINS = "https://winzi.stream,https://www.winzi.stream,http://localhost,http://127.0.0.1"

# Secrets (per wrangler secret put ...):
# TWITCH_CLIENT_ID
# TWITCH_CLIENT_SECRET
# KICK_APP_TOKEN   # optional
